language: r
os: linux
dist: xenial
cache: packages
branches:
  only:
  - master  # all others become PRs

r:
- oldrel
- release
- devel

apt_packages:
# Headers for Cairo.
- libcairo2-dev
- libjpeg-dev
## Headers for units
#- libudunits2-dev
## Dependencies for geojson→protolite
#- protobuf-compiler
#- libprotobuf-dev
## Dependencies for V8
#- libv8-3.14-dev
## Deps for jqr
#- libjq-dev
## Deps for rgdal
#- libgdal1-dev

install:
- >
  Rscript -e '
  all_deps = c("Depends", "Imports", "LinkingTo", "Suggests", "Enhances")
  deps <- remotes::dev_package_deps(dependencies = all_deps)
  remotes::update(deps[deps$package != "geojsonio", ])
  '

script:
- R CMD build .
- R CMD check repr*.tar.gz --as-cran
- cat "/home/travis/build/IRkernel/repr/repr.Rcheck/00check.log"
- cat "/home/travis/build/IRkernel/repr/repr.Rcheck/00install.out"
- grep -q -R 'WARNING' "/home/travis/build/IRkernel/repr/repr.Rcheck/00check.log" ; [ $? -ne 0 ]
# geojsonio is hard to install so we can’t check it
#- grep -q -R 'NOTE' "/home/travis/build/IRkernel/repr/repr.Rcheck/00check.log"; [ $? -ne 0 ]
- Rscript -e 'devtools::test(reporter="check")'
