language: r
sudo: false
cache: packages

r:
  - oldrel
  - release
  - devel

r_packages:
  # Enhanced packages
  - data.table
  - dplyr
  - htmlwidgets
  # Needed for building
  - roxygen2

addons:
  apt:
    packages:
      # Install the headers for the Cairo package.
      - libcairo2-dev
      - libjpeg-dev
      # Headers for geojson→protolite
      - libprotobuf-dev

script:
  - R CMD build .
  - R CMD check repr*.tar.gz --as-cran
  - cat "/home/travis/build/IRkernel/repr/repr.Rcheck/00check.log"
  - cat "/home/travis/build/IRkernel/repr/repr.Rcheck/00install.out"
  - grep -q -R 'WARNING' "/home/travis/build/IRkernel/repr/repr.Rcheck/00check.log" ; [ $? -ne 0 ]
  - grep -q -R 'NOTE' "/home/travis/build/IRkernel/repr/repr.Rcheck/00check.log"; [ $? -ne 0 ]
  - Rscript -e 'devtools::test(reporter="check")'
