language: r
distro: xenial  # needed for binary packages
sudo: true      # dito
cache: packages

r:
  - oldrel
  - release
  - devel

r_binary_packages:
  # Enhanced packages
  - data.table
  - dplyr
  - htmlwidgets
  - plotly
  # - geojsonio  # not available
  # Needed for building
  - roxygen2
  - devtools

addons:
  apt:
    packages:
      # Headers for Cairo.
      - libcairo2-dev
      - libjpeg-dev
      ## Headers for units
      #- libudunits2-dev
      ## Dependencies for geojson→protolite
      #- protobuf-compiler
      #- libprotobuf-dev
      ## Dependencies for V8
      #- libv8-3.14-dev
      ## Deps for jqr
      #- libjq-dev
      ## Deps for rgdal
      #- libgdal1-dev

script:
  - R CMD build .
  - R CMD check repr*.tar.gz --as-cran
  - cat "/home/travis/build/IRkernel/repr/repr.Rcheck/00check.log"
  - cat "/home/travis/build/IRkernel/repr/repr.Rcheck/00install.out"
  - grep -q -R 'WARNING' "/home/travis/build/IRkernel/repr/repr.Rcheck/00check.log" ; [ $? -ne 0 ]
  # geojsonio is hard to install so we can’t check it
  #- grep -q -R 'NOTE' "/home/travis/build/IRkernel/repr/repr.Rcheck/00check.log"; [ $? -ne 0 ]
  - Rscript -e 'devtools::test(reporter="check")'
